# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

jobs:
  include:
    - language: go
      go: 1.13.x
      name: "Linter"
      script:
        - make lint
        - rm -rf bindings/ # Avoid adding license to bindings
#        - make license-check
    - language: go
      go: 1.13.x
      name: "Test"
      script:
        - set -e
        - docker-compose -f ./docker-compose-chains.yml up -d
        - docker ps
        - make test
