# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'

services:
  celo1:
    image: "chainsafe/chainbridge-celo-blockchain"
    networks:
      custom:
        ipv4_address: 10.10.0.30
    container_name: celo1
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - NODEKEY=98ab333347a12cef869f92b3de44085f9e44891e513bcf1d76a99eecbcdd5e17

  celo2:
    image: "chainsafe/chainbridge-celo-blockchain"
    networks:
      - custom
    container_name: celo2
    ports:
      - "8645:8545"
      - "8646:8546"
    depends_on:
      - celo1
    environment:
      - ACCOUNTS=0xff93B45308FD417dF303D6515aB04D9e89a750Ca
      - BOOTNODE=enode://47eccabfa6fa81f7ae7d8c094485fd521789e22e529916a2409970b6e99b1d1b6c590ad71bd08f182071313b2e03d319f4f6b625b28b6ab7768bb2de3f2a6eed@10.10.0.30:30303

  celo3:
    image: "chainsafe/chainbridge-celo-blockchain"
    networks:
      - custom
    container_name: celo3
    ports:
      - "8745:8545"
      - "8746:8546"
    depends_on:
      - celo1
    environment:
      - ACCOUNTS=0x8e0a907331554AF72563Bd8D43051C2E64Be5d35
      - BOOTNODE=enode://47eccabfa6fa81f7ae7d8c094485fd521789e22e529916a2409970b6e99b1d1b6c590ad71bd08f182071313b2e03d319f4f6b625b28b6ab7768bb2de3f2a6eed@10.10.0.30:30303

#  celo-elections:
#    image: "chainsafe/chainbridge-celo-elections:20200928144404-87e4be2"
#    networks:
#      - custom
#    container_name: celo-elections
#    depends_on:
#      - celo1
#    environment:
#      - RPC_HOST=celo1

networks:
  custom:
    ipam:
      config:
      - subnet: 10.10.0.0/16
