on:
  pull_request:
    types: [opened, synchronize, reopened]

name: E2E tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run nodes
        run: docker-compose -f ./docker-compose-e2e.yml up -d
      - name: Run chainbridge
        run: ./scripts/start_bridge.sh
      - name: Run tests
        run: go test -p=1 $(go list ./... | grep 'e2e')